### ISSUE TITLE
not working on web!?

### ISSUE THREAD

**Issue by pejman-74** [spideythewebhead/flutterlifecyclehooks#1]
not working on web!?

**Comment by spideythewebhead** [comment]
Hello, i guess it doesn't work out of the box with the web. I can check it , but in a few days

**Comment by spideythewebhead** [comment]
Because this is a just a simple mixin that uses the API exposed from Flutter, thats why you cant use it on web, a solution might be copying this code and acces the web API to add the pause/resume functionally as when losing/gain focus on page? i will try to look into it
