### ISSUE TITLE
Missing / undocumented override of WidgetsBindingObserver.didPushRouteInformation

### ISSUE THREAD

**Issue by timosturm** [spideythewebhead/flutterlifecyclehooks#2]
This plugin cannot be used without overriding `WidgetsBindingObserver.didPushRouteInformation`:
```
  @override
  Future<bool> didPushRouteInformation(RouteInformation routeInformation) {
    // TODO: implement didPushRouteInformation
    throw UnimplementedError();
  }
```

This is not documented, and happens since updating to the new flutter version:
```
Flutter 1.22.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d408d302e2 (9 days ago) • 2020-09-29 11:49:17 -0700
Engine • revision 5babba6c4d
Tools • Dart 2.10.0
```

[This](https://api.flutter.dev/flutter/widgets/WidgetsBindingObserver/didPushRouteInformation.html) recommends to return `didPushRoute(routeInformation.location)`.

Is this supposed to be done by the user? Or handled by the plugin code?

**Comment by spideythewebhead** [comment]
Hello and thanks, i havent updated to 1.22 yet, but i think its a new function added to the `WidgetsBindingObserver`. 
I will check into it and i will have an upload probably today. I will make the default implementation on the `mixin` and always the programmer can override to add default behaviour

**Comment by spideythewebhead** [comment]
I have uploaded a new version
