### ISSUE TITLE
Add onInactive callback

### ISSUE THREAD

**Issue by thebedcoder** [spideythewebhead/flutterlifecyclehooks#5]
Hey, thanks for this package!
Could you add onInactive callback to the mixin, please? It should be 1 line change ☺️

**Comment by spideythewebhead** [comment]
Hi, sure I will have a look on that, with a possible release this week, thanks

**Comment by spideythewebhead** [comment]
@theRealGetman Hi, I have made a new release with the support of onInactive callback

**Comment by thebedcoder** [comment]
@spideythewebhead thank you so much for quick resolution!
